server:
  port: 80
  servlet:
    context-path: /morekaba
  tomcat:
    uri-encoding: UTF-8
    max-threads: 600
    max-connections: 12000

spring:
    datasource:
        #name: moerkaba
        #url: jdbc:mysql://rm-wz95q5f7xi208a2yz.mysql.rds.aliyuncs.com:3306/medicinefood?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
        #username: root
        #password: morekaba2018mdfd
        name: medicinefood
        url: jdbc:mysql://localhost:3306/medicinefood?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        resources: # 静态资源
        static-locations: classpath:/static/,classpath:/templates/
    devtools:
      restart:
        enabled: true
    servlet:
      multipart:
        enabled: true
        max-file-size: 600MB     #单个文件的最大上限
        max-request-size: 1000MB #单个请求的文件总大小上限

mybatis:
  type-aliases-package: com.morekaba.dao.modle
  mapper-locations: classpath:/mapper/*.xml,classpath:/shiromapper/*.xml #com/mrkb/dao/mapper/*.xml,classpath*:/mapper/**/*Mapper.xml
  #


#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql

#log4j配置文件
logging:
  config: classpath:log4j2-spring.xml


